# Site settings
title: Leaderboard GitPage
baseurl: ""  # the subpath of your site, e.g. "/my-github-username"
url: "https://illuminationZ.github.io"  # the base hostname & protocol for your site

# GitHub Pages configuration
theme: jekyll-theme-minimal
repository: leaderboard-gitpage
